"""Render the scoring-baseline validation summary as Markdown (used by validate_scoring_baseline.py)."""

from __future__ import annotations

from typing import Any

SEGMENT_TITLES = {
    "prior_games_min": "Prior games (fewer of the two teams)",
    "confidence_evidence": "Data confidence (reconstructed; availability assumed observed)",
    "confidence_published": "Data confidence (as it would have published; availability not observed)",
    "predicted_total": "Predicted total",
    "both_offenses_strong": "Both offenses strong (top FBS tercile, adjusted points)",
    "both_defenses_strong": "Both defenses strong (top FBS tercile, adjusted points allowed)",
    "strong_off_vs_strong_def": "A strong offense meets a strong defense",
    "strong_off_vs_weak_def": "A strong offense meets a weak defense",
    "conference_game": "Conference game",
    "fcs_involved": "FCS (or other non-FBS) team involved",
    "primary_total_environment": "PRIMARY script's scoring environment",
}


def _ci(ci: list[float] | None) -> str:
    return "–" if not ci else f"[{ci[0]:+.1f}, {ci[1]:+.1f}]"


def _cell(byd: dict[str, Any], key: str) -> str:
    return f"{byd[key]['bias']:+.2f} (n={byd[key]['n']})" if key in byd else "–"


def _row(name: str, st: dict[str, Any]) -> str:
    if not st.get("n"):
        return f"| {name} | 0 | | | | | | | |"
    return (
        f"| {name} | {st['n']} | {st['bias']:+.2f} | {_ci(st.get('bias_ci95'))} | {st['mae']:.2f} | "
        f"{st['rmse']:.2f} | {st['median_abs_error']:.1f} | {st['abs_error_p80']:.1f} | {st['abs_error_p90']:.1f} |"
    )


HEADER = (
    "| | N | Bias (pred − actual) | 95% CI | MAE | RMSE | Median AE | p80 AE | p90 AE |\n"
    "|---|---:|---:|---|---:|---:|---:|---:|---:|"
)


def render(summary: dict[str, Any]) -> str:
    out: list[str] = []
    out.append("# Scoring-baseline retrospective validation\n")
    out.append(
        f"Generated by `scripts/validate_scoring_baseline.py` (methodology `{summary['methodology_version']}`, "
        f"as of {summary['as_of']}). Protocol: {summary['protocol']}. Target: {summary['target']}.\n"
    )
    out.append(
        "Every prediction is `matchup.scoring_baseline` as production builds it, rebuilt per game from only the "
        "games that finished before that game's data cutoff. Errors are predicted − actual: a positive bias means "
        "the baseline ran **high**.\n"
    )
    out.append("## Totals by block\n")
    out.append(HEADER)
    for name, block in summary["blocks"].items():
        out.append(_row(name, block["total"]))
    out.append("")
    out.append(
        "| Block | Home pts bias | Home MAE | Away pts bias | Away MAE | Naive league total MAE "
        "| Excluded (no baseline) |"
    )
    out.append("|---|---:|---:|---:|---:|---:|---:|")
    for name, block in summary["blocks"].items():
        h, a, nv = block["home_points"], block["away_points"], block["naive_league_total"]
        out.append(
            f"| {name} | {h['bias']:+.2f} | {h['mae']:.2f} | {a['bias']:+.2f} | {a['mae']:.2f} | "
            f"{nv.get('mae', float('nan')):.2f} | {block['excluded_no_baseline']} |"
        )
    out.append("")
    out.append("## Defense double-counting test\n")
    out.append(
        "Per team-game OLS: `actual − mu − h·x = c + b_o·(adj_off − mu) + b_d·(adj_def_allowed − mu)`. "
        "b = 1: the baseline credits the unit exactly; b < 1: over-credited (double counted); b > 1: under-credited. "
        "[estimate, standard error].\n"
    )
    out.append("| Block | team-games | intercept c | b_offense | b_defense | bias vs opp. STRONG D | MID D | WEAK D |")
    out.append("|---|---:|---|---|---|---:|---:|---:|")
    for name, block in summary["blocks"].items():
        d = block["defense"]
        byd = d.get("team_points_bias_by_opponent_defense", {})
        out.append(
            f"| {name} | {d.get('n_team_games')} | {d.get('intercept')} | {d.get('b_offense')} | "
            f"{d.get('b_defense')} | {_cell(byd, 'STRONG')} | {_cell(byd, 'MID')} | {_cell(byd, 'WEAK')} |"
        )
    out.append("")
    out.append("## Segments\n")
    for seg, title in SEGMENT_TITLES.items():
        out.append(f"### {title}\n")
        out.append(HEADER)
        for name, block in summary["blocks"].items():
            for group, st in block["segments"].get(seg, {}).items():
                out.append(_row(f"{name} · {group}", st))
        out.append("")
    out.append("## Where the scripts' total bands sit, versus where totals landed\n")
    out.append(
        "For games whose PRIMARY script states a total band: mean (actual − baseline), mean (band centre − "
        "baseline), and how often the actual total fell inside the band.\n"
    )
    out.append("| Block | PRIMARY archetype | N | actual − baseline | band centre − baseline | Inside band |")
    out.append("|---|---|---:|---:|---:|---:|")
    for name, block in summary["blocks"].items():
        for arch, h in block["band_offsets"].items():
            out.append(
                f"| {name} | {arch} | {h['n']} | {h['actual_minus_baseline_mean']:+.1f} | "
                f"{h['band_centre_minus_baseline_mean']:+.1f} | {h['inside_band']} ({h['inside_rate']:.0%}) |"
            )
    out.append("")
    out.append("## Residual profile and home margin\n")
    out.append(
        "| Block | N | SD (actual − baseline) | p10 / p90 | p25 / p75 | corr(baseline, actual) | "
        "home effect applied | pred. home margin | actual home margin |"
    )
    out.append("|---|---:|---:|---|---|---:|---:|---:|---:|")
    for name, block in summary["blocks"].items():
        r = block["residuals"]
        out.append(
            f"| {name} | {r['n']} | {r['actual_minus_baseline_sd']:.1f} | {r['actual_minus_baseline_p10_p90']} | "
            f"{r['actual_minus_baseline_p25_p75']} | {r['corr_baseline_actual_total']:.3f} | "
            f"{r['home_effect_applied_mean']:+.2f} | {r['predicted_home_margin_mean']:+.2f} | "
            f"{r['actual_home_margin_mean']:+.2f} |"
        )
    out.append("")
    out.append("## Pre-registered corrections, out of sample\n")
    out.append(
        "Fitted on the training block only, scored on the untouched test block. `passes` is the retrospective half "
        "of the promotion gate (docs/SCRIPT_ENGINE.md 15.2 point 2): necessary, never sufficient.\n"
    )
    out.append(
        "| Split | Train → test | Method | Model | Test N | Bias | 95% CI | MAE | raw MAE | naive MAE "
        "| Failed checks | Passes |"
    )
    out.append("|---|---|---|---|---:|---:|---|---:|---:|---:|---|---|")
    for split, sp in summary["splits"].items():
        raw = sp["raw_baseline_on_test"]
        rows = [("raw baseline", {}, raw)] + [(m, c["model"], c["gate"]) for m, c in sp["corrections"].items()]
        for method, model, gate in rows:
            params = ", ".join(f"{k}={v}" for k, v in model.items() if k in ("a", "b", "c", "b_o", "b_d"))
            failed = [k for k, ok in gate["checks"].items() if not ok]
            out.append(
                f"| {split} | {'+'.join(sp['train'])} → {sp['test']} | {method} | {params or '–'} | "
                f"{gate.get('n', '')} | {gate['bias']:+.2f} | {_ci(gate['bias_ci95'])} | {gate['mae']:.2f} | "
                f"{gate['raw_mae_same_games']:.2f} | {gate['naive_mae_same_games']:.2f} | "
                f"{', '.join(failed) or 'none'} | {'yes' if gate['passes_retrospective_criteria'] else 'no'} |"
            )
    out.append("")
    out.append("## Inputs\n")
    for name, block in summary["blocks"].items():
        out.append(
            f"* **{name}**: {block['inputs']['rows']} team-game rows, fingerprint "
            f"`{block['inputs']['rows_fingerprint'][:16]}`; files {block['inputs']['files']}; "
            f"targets skipped {block['targets_skipped']}"
        )
    out.append("")
    return "\n".join(out)
